---

language: node_js

node_js:
  - lts/*

sudo: required

services:
  - docker

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-5-dev

install:
  - npm install @elementaryos/houston

script:
- houston ci
